name: Package and release

on:
  push:
    tags:
      - '**'

jobs:

  release:

    runs-on: ubuntu-22.04

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Create Package
        uses: BigWigsMods/packager@v2
        with:
          args: -n "{package-name}-{project-version}"
        
      - name: Create Package lastest
        uses: BigWigsMods/packager@v2
        with:
          args: -n "{package-name}"
